.catch((error) => {
    console.log('Error: ', error);
});
